### ISSUE TITLE
Problem when yarn run changes files in resource

### ISSUE THREAD

**Issue by SudoGetBeer** [WilberGroup/airdrop#2]
Hey,
First of all really like this package.

So I had a little Problem with using it in our deployments because we are using ziggy in the project and it creates a file in resources.
The problem was finding this different file.

So I thought I could add a option to the download and upload command so they make a diff of the `HashGenerator::make()->asArray()`
so it could be easier to find the differences.

Would you be open to a PR with this functionality? Then I would try to add it in the next days.

**Comment by aarondfrancis** [comment]
Mmm I see what you're saying. It was functioning correctly, but hard to figure out _why_ it kept recompiling. Interesting.

The tricky part about this is Airdrop doesn't keep a record of anything anywhere (which is a feature).

So you can't really just download the last archive that was uploaded and compare files, because 

1) you don't know which one that was and 
2) the files may match and some other input may be different, but we don't store those inputs anywhere.

Everything is based on the resultant hash, all the parts used to build that hash are not kept around in the ZIP artifact.

Does that make sense? If so, is there a workaround you can think of?

Re: Ziggy, you do want to regenerate assets whenever the `ziggy.js` changes, right? Because that means some of your routes changed? If not, you can add `ziggy.js` to the ignore section. (I know you're suggesting a more general package feature, but wanted to address this specifically!)

**Comment by aarondfrancis** [comment]
I suppose it's possible we could put an `airdrop.json` file in the ZIP artifact. Then at least you could manually debug it by comparing the two? You wouldn't be able to do it automatically because you still don't know which package is the latest one.

**Comment by SudoGetBeer** [comment]
> Re: Ziggy, you do want to regenerate assets whenever the ziggy.js changes, right? Because that means some of your routes changed? If not, you can add ziggy.js to the ignore section. (I know you're suggesting a more general package feature, but wanted to address this specifically!)

Yeah after I found out why that was the solution 😅
It helped to print out the file name which was generated in both command with the verbose option.

> I suppose it's possible we could put an airdrop.json file in the ZIP artifact. Then at least you could manually debug it by comparing the two? You wouldn't be able to do it automatically because you still don't know which package is the latest one.

Yeah but that would not help really.
Maybe add a command which dumps out the files in a file. Something like this would help to debug I think:

```
Php artisan airdrop:files before.json 

Npm run prod 

Php artisan airdrop:files after.json

Diff before.json after.json
```


And this should only be available to debug which files to exclude.

**Comment by aarondfrancis** [comment]
Ahhhh, I understand what you're saying now. 

Let me think on it for a bit, but I feel generally positive about it at the moment.

Good idea.

**Comment by aarondfrancis** [comment]
@SudoGetBeer take a look at https://github.com/hammerstonedev/airdrop/pull/3 and let me know what you think!

**Comment by SudoGetBeer** [comment]
Looks good 👍

Would have helped me

**Comment by aarondfrancis** [comment]
Merged. Thanks for the idea!
